import type { IconType } from "react-icons";
import {
  SiPython,
  SiFastapi,
  SiSqlalchemy,
  SiPostgresql,
  SiRedis,
  SiReact,
  SiLangchain,
  SiDocker,
  SiGithubactions,
  SiGit,
  SiPytest,
  SiTensorflow,
  SiScikitlearn,
  SiPandas,
  SiNumpy,
  SiPlotly,
  SiHtml5,
  SiCss,
  SiJavascript,
} from "react-icons/si";
import { DiJava } from "react-icons/di";
import {
  LuNetwork,
  LuRadio,
  LuBrain,
  LuLibrary,
  LuWorkflow,
  LuPlug,
  LuZap,
  LuArrowRightLeft,
  LuUserCheck,
  LuBrainCircuit,
  LuLayers,
  LuChartLine,
} from "react-icons/lu";

export const skillIcons: Record<string, IconType> = {
  Python: SiPython,
  Java: DiJava,
  FastAPI: SiFastapi,
  "REST APIs": LuNetwork,
  SQLAlchemy: SiSqlalchemy,
  PostgreSQL: SiPostgresql,
  Redis: SiRedis,
  SSE: LuRadio,
  React: SiReact,
  HTML: SiHtml5,
  CSS: SiCss,
  JavaScript: SiJavascript,

  LLMs: LuBrain,
  RAG: LuLibrary,
  LangGraph: LuWorkflow,
  LangChain: SiLangchain,
  MCP: LuPlug,
  FastMCP: LuZap,
  A2A: LuArrowRightLeft,
  HITL: LuUserCheck,

  Docker: SiDocker,
  "GitHub Actions": SiGithubactions,
  Git: SiGit,
  pytest: SiPytest,

  "Machine Learning": LuBrainCircuit,
  "Deep Learning": LuLayers,
  TensorFlow: SiTensorflow,
  "scikit-learn": SiScikitlearn,
  Pandas: SiPandas,
  NumPy: SiNumpy,
  Matplotlib: LuChartLine,
  Plotly: SiPlotly,
};
